description: >
  This command echos "Hello World" using file inclusion.
parameters:
  install-kubectl:
    type: boolean
    default: false
    description: Whether to install kubectl
  install-tccli:
    type: boolean
    default: true
    description: Whether to install tccli
  cluster-id:
    type: string
    description: The id of the cluster for which to create a kubeconfig entry.
steps:
  - jq/install
  - when:
      condition: << parameters.install-kubectl >>
      steps:
        - kubernetes/install
  - when:
      condition: << parameters.install-tccli >>
      steps:
        - setup-tccli
  - run:
      name: setup $HOME/.kube/config
      command: |
        if [ ! -d $HOME/.kube ]; then
          mkdir $HOME/.kube
        fi
        cd $HOME/.kube

        tccli tke DescribeClusterKubeconfig --ClusterId << parameters.cluster-id >> > tke-config.json
        echo -e "$(cat tke-config.json | jq '.Kubeconfig' | sed -e 's/\\"/"/g'  -e 's/"//')" | head -n -2 > config
        kube config use-context $(kubectl config get-contexts | awk '{print $2}' | sed -n 2P)
